# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d943fbd52ecd512f019b3589e5b0132e9af2ea882312c399235f201a2aa3e2f899596e3571e2eeda06f1ed41ed63e6105c16a48e5327bdcb0c6286710ed9890

test:
  secret_key_base: c01af8d941d8cc60e0e4238a0ac64f7e5c9d761d742c2456ede492c7fd343ecf47232205d8318d6022633deaae4ff34128b5c6cd195eba5a3d4564dc8a1c7a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
